# Test your FastAPI endpoints
GET http://127.0.0.1:8000/consumer-report/v1/echo/boogers
Accept: application/json


###


POST http://127.0.0.1:8000/consumer-report/v1/product/query
Content-Type: application/json
Accept: application/json

{
   "product_name": "Victron Energy BMV-712 Smart Battery Monitor"
}
