aws_region                  = "us-east-1"
lambda_function_name        = "consumer-reports-api"
lambda_handler              = "main.handler"
lambda_runtime              = "python3.9"
lambda_zip_file_path        = "dist/"
lambda_zip_file_name        = "consumer-reports-lambda.zip"
# s3_artifacts_bucket_key     = "pfx"
s3_artifacts_bucket_name    = "lambdafacts"
openai_api_key              = "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"
tags                        = { tag-key = "consumer-reports" }